apiVersion: v1
kind: Pod
metadata:
  name: podname
spec:
  containers:
  - name: podname
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: cm
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: cm
    configMap:
      name: my-config