apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      a: b
# POd defination
  template:
    metadata:
      labels:
        a: b
    spec:
      containers:
      - name: ninx
        image: nginx
        
